
# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# configure supernova
/Inputs/Particle_Type SUPERNOVA

# output path
/Inputs/root_output K40_background.root

# initialize run
/run/initialize
/random/setSeeds 137 1000

# event ID offset
/event/offset 0

# Supernova configs
/Supernova/Event_Window 0.001 s
/Supernova/Event_Cutoff 0.001 s

/Supernova/N_K40_Decays 1

# run
/run/beamOn 10000
